sudo: required

service:
  - docker

before_install:
  - docker build -t produc -f Dockerfile.dev .

script:
  - docker run -e CI=true produc npm run test


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "docker-demo"
  env: "Dockerdemo-env"
  bucket_name: "elasticbeanstalk-us-east-2-712681526452"
  on:
    branch: master